# Generated by Django 2.2.6 on 2019-10-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('UID', models.CharField(max_length=20)),
                ('course', models.CharField(choices=[('BCA', 'BCA'), ('MCA', 'MCA'), ('B.TECH', 'B.Tech'), ('BSC', 'bsc'), ('MBBS', 'Mbbs'), ('B.COM', 'B.Com'), ('M.COM', 'M.Com'), ('MSC', 'Msc'), ('PHD', 'Phd'), ('M.TECH', 'M.Tech'), ('MS', 'Ms')], max_length=20)),
                ('semester', models.CharField(choices=[('First', 'I'), ('Secoond', 'II'), ('Third', 'III'), ('Fourth', 'IV'), ('Five', 'V'), ('Six', 'VI'), ('Sevan', 'VII'), ('Eight', 'VIII')], max_length=10)),
                ('email', models.EmailField(max_length=250)),
                ('mobile', models.IntegerField()),
            ],
        ),
    ]
