# Generated by Django 2.2.6 on 2019-10-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('First', 'I'), ('Second', 'II'), ('Third', 'III'), ('Fourth', 'IV'), ('Five', 'V'), ('Six', 'VI'), ('Sevan', 'VII'), ('Eight', 'VIII')], max_length=20),
        ),
    ]
