# Generated by Django 2.2.6 on 2019-10-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_auto_20191015_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('BCA', 'BCA'), ('MCA', 'MCA'), ('B.TECH', 'B.Tech'), ('BSC', 'bsc'), ('MBBS', 'Mbbs'), ('B.COM', 'B.Com'), ('M.COM', 'M.Com'), ('MSC', 'Msc'), ('PHD', 'Phd'), ('M.TECH', 'M.Tech'), ('MS', 'Ms')], max_length=25),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
