# Generated by Django 2.2.6 on 2019-10-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_auto_20191015_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('BCA', 'BCA'), ('MCA', 'MCA'), ('B.TECH', 'B.Tech'), ('BSC', 'bsc'), ('MBBS', 'Mbbs'), ('B.COM', 'B.Com'), ('M.COM', 'M.Com'), ('MSC', 'Msc'), ('PHD', 'Phd'), ('M.TECH', 'M.Tech'), ('MS', 'Ms')], default='BCA', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('First', 'I'), ('Second', 'II'), ('Third', 'III'), ('Fourth', 'IV'), ('Five', 'V'), ('Six', 'VI'), ('Sevan', 'VII'), ('Eight', 'VIII')], default='First', max_length=20, null=True),
        ),
    ]
