# Generated by Django 2.2.6 on 2019-10-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Class',
            field=models.CharField(choices=[('Computer Science and Engineering', 'CSE'), ('Electronics and Communication Engineering', 'ECE'), ('Electrical Engineering', 'EE'), ('Mechanical Engineering', 'ME'), ('Civil Engineering', 'CIVIL E'), ('Petroleum Engineering', 'PE'), ('Chemical Engineering', 'CE'), ('Aerospace Engineering', 'AE'), ('Industrial Engineering', 'IE'), ('Aeronautical Engineering', 'AERO E'), ('Medical', 'MEDICAL'), ('Finance', 'FFNANCE'), ('Computer Application', 'Comp App')], max_length=45),
        ),
        migrations.AlterField(
            model_name='book',
            name='grade',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=2),
        ),
    ]
