# Generated by Django 2.2.6 on 2019-10-16 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Student', '0001_initial'),
        ('Books', '0001_initial'),
        ('LendBook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField()),
                ('Fine', models.IntegerField()),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.Book')),
                ('LendBook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LendBook.LendBook')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Student')),
            ],
        ),
    ]
